// Generic connector conformance suite — backend-agnostic vitest cases that any
// `Connector` implementation must satisfy. Call describeConnectorContract(name,
// connector, opts) from a `<connector>/conformance.test.ts` to get a baseline of
// contract-shape and round-trip checks for free; keep connector-specific scenarios
// (mapping edge cases, cross-field validation rules, etc.) in that connector's own
// mapping.test.ts.
//
// What this DOESN'T do: it can't know a connector's domain rules (e.g. Acme's
// "critical bugs need repro steps"), so it sticks to invariants the contract itself
// promises — shape, status vocabulary, attribute catalog, and read-after-write
// round-trips for push/createItem.

import { beforeEach, describe, expect, it } from 'vitest';
import type { ConnectorItemType, FieldSpec, MappedRelease } from '../contract.js';
import { isAttributeField } from '../lib/attributes.js';
import { ValidationError } from '../lib/validate.js';
import type { Connector, CreateItemInput } from './types.js';

const CANONICAL_STATUSES = ['Not Started', 'In Progress', 'Under Review', 'Blocked', 'Complete'] as const;

/** True if `value`'s runtime type matches a FieldSpec's declared `kind` (or is null). */
function kindMatches(kind: FieldSpec['kind'], value: unknown): boolean {
  if (value === null) return true;
  switch (kind) {
    case 'number':
      return typeof value === 'number';
    case 'boolean':
      return typeof value === 'boolean';
    case 'string':
    case 'date':
    case 'enum':
      return typeof value === 'string';
    default:
      return true;
  }
}

/** A representative value for a creatable field, used to build a generically-valid create request. */
function sampleValue(f: FieldSpec): unknown {
  switch (f.kind) {
    case 'string':
      return f.multiline ? 'Generated by the connector conformance suite.' : `Conformance check: ${f.label ?? f.key}`;
    case 'number':
      return f.min ?? 1;
    case 'boolean':
      return true;
    case 'date':
      return '2026-01-01';
    case 'enum':
      return f.enumRef === 'status' ? 'Not Started' : f.options?.[0]?.value;
    default:
      return undefined;
  }
}

/** An empty-but-well-typed create request for `type` — every required field omitted. */
function buildEmptyCreateRequest(type: ConnectorItemType): CreateItemInput {
  return { type: type.id, extWorkStreamId: null, extSprintId: null, extAssigneeId: null, fields: {} };
}

/**
 * A create request for `type` with every required creatable field populated, using
 * entities from `release` for ref fields. Returns null if a required ref field's
 * target collection is empty (the suite can't satisfy it generically).
 */
function buildValidCreateRequest(type: ConnectorItemType, release: MappedRelease): CreateItemInput | null {
  const req: CreateItemInput = { type: type.id, extWorkStreamId: null, extSprintId: null, extAssigneeId: null, fields: {} };
  const fields = req.fields as Record<string, unknown>;

  for (const f of type.fields) {
    if (!f.creatable || !f.required) continue;

    if (f.kind === 'ref') {
      const pool =
        f.target === 'workStream' ? release.workStreams : f.target === 'sprint' ? release.sprints : f.target === 'member' ? (release.team?.members ?? []) : [];
      const id = pool[0]?.externalId;
      if (!id) return null;
      if (f.target === 'workStream') req.extWorkStreamId = id;
      else if (f.target === 'sprint') req.extSprintId = id;
      else if (f.target === 'member') req.extAssigneeId = id;
      continue;
    }

    fields[f.key] = sampleValue(f);
  }

  return req;
}

export interface ConformanceOptions {
  /** Non-secret config to pass to validate/fetchAndMap/push/createItem. Defaults to {}. */
  config?: Record<string, string>;
  /** Reset connector-owned state between tests (e.g. an in-process warehouse). Return value ignored. */
  reset?: () => unknown;
}

/**
 * Generic contract-conformance cases for one Connector. Mirrors the invariants the
 * sync-contract OpenAPI spec promises: meta shape, fetchAndMap output (canonical
 * statuses, status vocabulary, attribute catalog), and push/createItem round-trips.
 */
export function describeConnectorContract(name: string, connector: Connector, opts: ConformanceOptions = {}): void {
  const config = opts.config ?? {};

  describe(`${name} connector contract conformance`, () => {
    beforeEach(async () => {
      await opts.reset?.();
    });

    describe('meta', () => {
      it('declares type, label, and configFields', () => {
        expect(connector.meta.type).toBeTruthy();
        expect(connector.meta.label).toBeTruthy();
        expect(Array.isArray(connector.meta.configFields)).toBe(true);
      });

      it('itemTypes (if any) have unique ids and well-formed FieldSpecs', () => {
        const itemTypes = connector.meta.itemTypes ?? [];
        const ids = itemTypes.map((t) => t.id);
        expect(new Set(ids).size).toBe(ids.length);

        for (const type of itemTypes) {
          expect(type.id).toBeTruthy();
          expect(type.label).toBeTruthy();
          const keys = type.fields.map((f) => f.key);
          expect(new Set(keys).size).toBe(keys.length);

          for (const f of type.fields) {
            expect(f.key).toBeTruthy();
            expect(['string', 'number', 'boolean', 'date', 'enum', 'ref']).toContain(f.kind);
            if (f.kind === 'ref') expect(['workStream', 'sprint', 'member']).toContain(f.target);
            if (f.kind === 'enum' && !f.enumRef) expect((f.options ?? []).length).toBeGreaterThan(0);
          }
        }
      });

      it('statuses (if any) have unique ids and a canonical category', () => {
        const statuses = connector.meta.statuses ?? [];
        const ids = statuses.map((s) => s.id);
        expect(new Set(ids).size).toBe(ids.length);

        for (const s of statuses) {
          expect(s.id).toBeTruthy();
          expect(s.label).toBeTruthy();
          expect(CANONICAL_STATUSES).toContain(s.category);
        }
      });
    });

    describe('validate', () => {
      it('returns a ValidateResult shape', async () => {
        const result = await connector.validate(config);
        expect(typeof result.ok).toBe('boolean');
      });
    });

    describe('fetchAndMap', () => {
      it('returns workStreams, sprints, and items arrays', async () => {
        const release = await connector.fetchAndMap(config);
        expect(Array.isArray(release.workStreams)).toBe(true);
        expect(Array.isArray(release.sprints)).toBe(true);
        expect(Array.isArray(release.items)).toBe(true);
      });

      it('reading twice is side-effect free', async () => {
        const a = await connector.fetchAndMap(config);
        const b = await connector.fetchAndMap(config);
        expect(b.items.length).toBe(a.items.length);
        expect(b.workStreams.length).toBe(a.workStreams.length);
        expect(b.sprints.length).toBe(a.sprints.length);
      });

      it('every item has a canonical status', async () => {
        const release = await connector.fetchAndMap(config);
        for (const item of release.items) {
          expect(CANONICAL_STATUSES).toContain(item.fields.status);
        }
      });

      it('extWorkStreamId / extSprintId resolve to entries in workStreams / sprints, or null', async () => {
        const release = await connector.fetchAndMap(config);
        const wsIds = new Set(release.workStreams.map((w) => w.externalId));
        const spIds = new Set(release.sprints.map((s) => s.externalId));
        for (const item of release.items) {
          if (item.extWorkStreamId != null) expect(wsIds.has(item.extWorkStreamId)).toBe(true);
          if (item.extSprintId != null) expect(spIds.has(item.extSprintId)).toBe(true);
        }
      });

      it('statusNative (if present) is declared in meta.statuses and its category matches fields.status', async () => {
        const release = await connector.fetchAndMap(config);
        const statuses = connector.meta.statuses ?? [];
        for (const item of release.items) {
          const native = item.fields.statusNative;
          if (native == null) continue;
          const def = statuses.find((s) => s.id === native.id);
          expect(def, `statusNative.id "${native.id}" must be declared in meta.statuses`).toBeTruthy();
          expect(def!.label).toBe(native.label);
          expect(def!.category).toBe(item.fields.status);
        }
      });

      it('item attributes (if present) are declared vocabulary fields, kind-coerced', async () => {
        const release = await connector.fetchAndMap(config);
        const itemTypes = connector.meta.itemTypes ?? [];
        for (const item of release.items) {
          if (!item.attributes) continue;
          const typeId = item.fields.itemType?.id;
          const type = itemTypes.find((t) => t.id === typeId);
          expect(type, `item type "${typeId}" must be declared in meta.itemTypes`).toBeTruthy();

          for (const [key, value] of Object.entries(item.attributes)) {
            const field = type!.fields.find((f) => f.key === key);
            expect(field, `attribute "${key}" must be declared on item type "${typeId}"`).toBeTruthy();
            expect(isAttributeField(field!)).toBe(true);
            expect(kindMatches(field!.kind, value)).toBe(true);
          }
        }
      });
    });

    describe('capability honesty', () => {
      it('createItem is implemented iff at least one item type declares a creatable field', () => {
        const hasCreatable = (connector.meta.itemTypes ?? []).some((t) => t.fields.some((f) => f.creatable));
        if (hasCreatable) expect(connector.createItem).toBeTypeOf('function');
        if (!connector.createItem) expect(hasCreatable).toBe(false);
      });
    });

    describe('createItem', () => {
      const itemTypes = connector.meta.itemTypes ?? [];
      const creatableTypes = itemTypes.filter((t) => t.fields.some((f) => f.creatable));

      if (!connector.createItem || creatableTypes.length === 0) {
        it.skip('connector does not support item creation', () => {});
        return;
      }
      const createItem = connector.createItem.bind(connector);

      it('rejects an empty create request with field-keyed errors for required creatable fields (422 path)', async () => {
        const type = creatableTypes.find((t) => t.fields.some((f) => f.creatable && f.required)) ?? creatableTypes[0];
        const requiredKeys = type.fields.filter((f) => f.creatable && f.required).map((f) => f.key);
        if (requiredKeys.length === 0) return;

        const req = buildEmptyCreateRequest(type);
        const failure = await createItem(config, req).then(
          () => null,
          (e: unknown) => e,
        );
        expect(failure).toBeInstanceOf(ValidationError);
        const errFields = (failure as ValidationError).fieldErrors.map((fe) => fe.field);
        for (const key of requiredKeys) expect(errFields).toContain(key);
      });

      it('creates an item from a valid request and the new item appears on the next sync', async () => {
        const release = await connector.fetchAndMap(config);
        let built: { type: ConnectorItemType; req: CreateItemInput } | null = null;
        for (const type of creatableTypes) {
          const req = buildValidCreateRequest(type, release);
          if (req) {
            built = { type, req };
            break;
          }
        }
        if (!built) return; // no item type's required refs could be satisfied generically

        const created = await createItem(config, built.req);
        expect(created.externalId).toBeTruthy();
        expect(created.fields.key).toBeTruthy();
        expect(CANONICAL_STATUSES).toContain(created.fields.status);
        if (created.fields.itemType) expect(created.fields.itemType.id).toBe(built.type.id);

        const synced = await connector.fetchAndMap(config);
        expect(synced.items.some((i) => i.externalId === created.externalId)).toBe(true);
      });
    });

    describe('push', () => {
      if (!connector.push) {
        it.skip('connector does not support push', () => {});
        return;
      }
      const push = connector.push.bind(connector);

      it('pushing no changes is a no-op', async () => {
        expect(await push(config, [])).toEqual({ pushed: 0, failed: 0, errors: [] });
      });

      it('reports an unknown externalId as failed without throwing', async () => {
        const result = await push(config, [{ externalId: 'NOPE-DOES-NOT-EXIST', fields: { points: 1 } }]);
        expect(result.pushed).toBe(0);
        expect(result.failed).toBeGreaterThanOrEqual(1);
      });

      it('ignores an undeclared statusId / attribute key without failing the item', async () => {
        const release = await connector.fetchAndMap(config);
        const item = release.items[0];
        if (!item) return;

        const result = await push(config, [
          { externalId: item.externalId, fields: { statusId: 'not-a-real-status-id', attributes: { notARealAttributeKey: 'x' } } },
        ]);
        expect(result.failed).toBe(0);
      });

      it('a writeable points field round-trips on the next sync', async () => {
        const release = await connector.fetchAndMap(config);
        const itemTypes = connector.meta.itemTypes ?? [];
        const item = release.items.find((i) => {
          const type = itemTypes.find((t) => t.id === i.fields.itemType?.id);
          return type?.fields.some((f) => f.role === 'points' && f.writeable);
        });
        if (!item) return; // connector declares no writeable points field

        const newPoints = (item.fields.points ?? 0) + 1;
        const result = await push(config, [{ externalId: item.externalId, fields: { points: newPoints } }]);
        expect(result).toEqual({ pushed: 1, failed: 0, errors: [] });

        const synced = await connector.fetchAndMap(config);
        expect(synced.items.find((i) => i.externalId === item.externalId)?.fields.points).toBe(newPoints);
      });
    });
  });
}
