/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available connectors and the config each one needs. */
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connectors/{type}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a connector's config (and optionally creds) before saving. */
        post: operations["validateConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch + map external data for a release into the app's schema. */
        post: operations["syncRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The app's four canonical work-item statuses. The service must coerce to one of these.
         * @enum {string}
         */
        Status: "Not Started" | "Active" | "Blocked" | "Complete";
        MappedWorkStream: {
            externalId: string;
            fields: {
                name: string;
            };
        };
        MappedSprint: {
            externalId: string;
            fields: {
                name: string;
                /** @description YYYY-MM-DD */
                startISO: string;
                /** @description YYYY-MM-DD */
                endISO: string;
            };
        };
        MappedItem: {
            externalId: string;
            /** @description External epic id; the app resolves it to a local work stream. */
            extWorkStreamId: string | null;
            /** @description External sprint id; the app resolves it to a local sprint number. */
            extSprintId: string | null;
            fields: {
                /** @description External-provided, e.g. ATL-123 */
                key: string;
                subject: string;
                description: string;
                status: components["schemas"]["Status"];
                points: number;
            };
        };
        /** @description The sync payload for one release. Normalized, keyed by externalId. */
        MappedRelease: {
            workStreams: components["schemas"]["MappedWorkStream"][];
            sprints: components["schemas"]["MappedSprint"][];
            items: components["schemas"]["MappedItem"][];
        };
        ConnectorConfigField: {
            key: string;
            label: string;
            required: boolean;
            hint?: string;
        };
        ConnectorMeta: {
            /** @description e.g. 'jira' */
            type: string;
            /** @description e.g. 'Jira' */
            label: string;
            configFields: components["schemas"]["ConnectorConfigField"][];
        };
        /** @description A release's binding to a backend. config holds only non-secret routing params. */
        ReleaseConnector: {
            type: string;
            config: {
                [key: string]: string;
            };
        };
        ValidateRequest: {
            config: {
                [key: string]: string;
            };
        };
        ValidateResult: {
            ok: boolean;
            error?: string;
        };
        SyncRequest: {
            connector: components["schemas"]["ReleaseConnector"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available connectors. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorMeta"][];
                };
            };
        };
    };
    validateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Validation outcome. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResult"];
                };
            };
        };
    };
    syncRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description The mapped release payload. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappedRelease"];
                };
            };
        };
    };
}
